"""Shared runtime constants for mdexplore."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
GLOBAL_SETTINGS_FILE = PROJECT_ROOT / "mdexplore.settings.json"

_DEFAULTS: dict[str, Any] = {
    "CONFIG_FILE_NAME": ".mdexplore.cfg",
    "UI_ASSET_DIR_RELATIVE": "assets/ui",
    "JS_ASSET_DIR_RELATIVE": "assets/js",
    "TEMPLATE_ASSET_DIR_RELATIVE": "assets/templates",
    "SEARCH_CLOSE_WORD_GAP": 50,
    "PDF_LANDSCAPE_PAGE_TOKEN": "MDEXPLORE_LANDSCAPE_PAGE_TOKEN",
    "PDF_EXPORT_PRECHECK_MAX_ATTEMPTS": 60,
    "PDF_EXPORT_PRECHECK_INTERVAL_MS": 140,
    "MERMAID_CACHE_JSON_TOKEN": "__MDEXPLORE_MERMAID_CACHE_JSON__",
    "DIAGRAM_VIEW_STATE_JSON_TOKEN": "__MDEXPLORE_DIAGRAM_VIEW_STATE_JSON__",
    "MERMAID_SVG_CACHE_MAX_ENTRIES": 256,
    "MERMAID_SVG_MAX_CHARS": 250_000,
    "PLANTUML_RESTORE_BATCH_SIZE": 2,
    "MERMAID_CACHE_RESTORE_BATCH_SIZE": 2,
    "RESTORE_OVERLAY_TIMEOUT_SECONDS": 25.0,
    "RESTORE_OVERLAY_SHOW_DELAY_MS": 350,
    "RESTORE_OVERLAY_MAX_VISIBLE_SECONDS": 1.0,
    "MERMAID_BACKEND_JS": "js",
    "MERMAID_BACKEND_RUST": "rust",
    "MIN_PRINT_DIAGRAM_FONT_PT": 3,
    "MAX_PRINT_DIAGRAM_FONT_PT": 12.0,
    "PDF_PRINT_HEADING_TO_DIAGRAM_GAP_PX": 16,
    "PDF_PRINT_LAYOUT_SAFETY_PX": 40,
    "PDF_PRINT_KEEP_MIN_HEIGHT_PX": 120,
    "PDF_PRINT_PORTRAIT_LETTER_WIDTH_PX": 1000,
    "PDF_PRINT_PORTRAIT_LETTER_HEIGHT_PX": 1310,
    "PDF_PRINT_LANDSCAPE_LETTER_WIDTH_PX": 1100,
    "PDF_PRINT_LANDSCAPE_LETTER_HEIGHT_PX": 860,
    "PDF_PRINT_HORIZONTAL_MARGIN_PX": 80,
    "PDF_PRINT_VERTICAL_MARGIN_PX": 130,
    "PDF_PRINT_PORTRAIT_MIN_WIDTH_PX": 320,
    "PDF_PRINT_PORTRAIT_MIN_HEIGHT_PX": 320,
    "PDF_PRINT_LANDSCAPE_MIN_WIDTH_PX": 360,
    "PDF_PRINT_LANDSCAPE_MIN_HEIGHT_PX": 260,
    "PDF_PRINT_WIDE_DIAGRAM_ASPECT_RATIO": 1.19,
    "PDF_PRINT_WIDE_DIAGRAM_LANDSCAPE_GAIN": 1.06,
    "PDF_PRINT_PLANTUML_LANDSCAPE_ASPECT_RATIO": 1.18,
    "PREVIEW_SETHTML_MAX_BYTES": 650_000,
    "SVG_ICON_RENDER_OVERSAMPLE": 4,
    "SVG_ICON_ALPHA_CUTOFF": 1,
    "SEARCH_HIT_COUNT_FONT_PATHS": [
        "assets/ui/LiberationSansNarrow-Regular.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf",
    ],
    "PREVIEW_PERSISTENT_HIGHLIGHT_COLOR": "rgba(102, 86, 178, 0.36)",
    "PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_COLOR": "rgba(225, 214, 255, 0.76)",
    "PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_TEXT_COLOR": "#170534",
    "PREVIEW_PERSISTENT_HIGHLIGHT_MARKER_COLOR": "rgba(112, 90, 188, 0.92)",
    "PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_MARKER_COLOR": "rgba(154, 132, 220, 0.96)",
    "PREVIEW_HIGHLIGHT_KIND_NORMAL": "normal",
    "PREVIEW_HIGHLIGHT_KIND_IMPORTANT": "important",
    "PREVIEW_ZOOM_STEP": 0.1,
    "PREVIEW_ZOOM_MIN": 0.35,
    "PREVIEW_ZOOM_MAX": 3.0,
    "PREVIEW_ZOOM_RESET": 1.0,
    "PREVIEW_ZOOM_OVERLAY_TIMEOUT_MS": 850,
    "MDEXPLORE_MAX_DOCUMENT_VIEWS": 8,
    "MDEXPLORE_MAX_RECENT_ROOT_DIRECTORIES": 35,
    "MDEXPLORE_RECENT_ROOT_MENU_MRU_COUNT": 10,
    "MDEXPLORE_MIN_RECENT_ROOT_DWELL_SECONDS": 30.0,
    "MDEXPLORE_CONFIG_LOCK_STALE_SECONDS": 120.0,
    "MDEXPLORE_VIEWS_FILE_NAME": ".mdexplore-views.json",
    "MDEXPLORE_HIGHLIGHTING_FILE_NAME": ".mdexplore-highlighting.json",
    "MDEXPLORE_CONFIG_DEFAULT_ROOT_KEY": "default_root",
    "MDEXPLORE_CONFIG_RECENT_ROOTS_KEY": "recent_roots",
    "MDEXPLORE_CONFIG_COPY_BASE64_IMAGES_ENABLED_KEY": "copy_base64_images_enabled",
    "MDEXPLORE_DEBUG_LOG_FILE_NAME": "mdexplore.log",
    "MDEXPLORE_DEBUG_LOG_MAX_LINES": 10000,
    "MDEXPLORE_HIGHLIGHT_COLORS": [
        ["Yellow", "#f5d34f"],
        ["Green", "#78d389"],
        ["Blue", "#7bb9ff"],
        ["Orange", "#f6a05f"],
        ["Purple", "#bb9df5"],
        ["Light Gray", "#d1d5db"],
        ["Medium Gray", "#9ca3af"],
        ["Red", "#ef7d7d"],
    ],
    "MDEXPLORE_DEFAULT_SEARCH_SCAN_MAX_THREADS": 0,
    "MDEXPLORE_DEFAULT_BASE64_IMAGE_WORKER_THREADS": 0,
    "MDEXPLORE_PREVIEW_HTTP_CACHE_MAX_BYTES": 4294967296,
    "MDEXPLORE_PREVIEW_HTTP_CACHE_MAX_BYTES_QT_MAX": 2147483647,
    "MDEXPLORE_PREVIEW_HTTP_CACHE_MIN_BYTES": 67108864,
    "MDEXPLORE_PREVIEW_HTTP_CACHE_FREE_SPACE_RESERVE_BYTES": 536870912,
    "MDEXPLORE_PREVIEW_WEBENGINE_INSTANCE_STALE_SECONDS": 172800,
    "MDEXPLORE_INLINE_DATA_IMAGE_POOL_THREADS": 1,
    "MDEXPLORE_TREE_MARKER_SCAN_POOL_THREADS": 1,
    "MDEXPLORE_PLANTUML_POOL_MAX_THREADS": 6,
    "MDEXPLORE_PDF_POOL_MAX_THREADS": 1,
    "MDEXPLORE_MATCH_TIMER_INTERVAL_MS": 3000,
    "MDEXPLORE_TREE_SEARCH_REFRESH_DEBOUNCE_MS": 180,
    "MDEXPLORE_SCROLL_CAPTURE_INTERVAL_MS": 200,
    "MDEXPLORE_DIAGRAM_STATE_CAPTURE_INTERVAL_MS": 250,
    "MDEXPLORE_PREVIEW_ACTION_POLL_INTERVAL_MS": 220,
    "MDEXPLORE_STATUS_IDLE_INTERVAL_MS": 900,
    "MDEXPLORE_FILE_CHANGE_WATCH_INTERVAL_MS": 1200,
    "MDEXPLORE_RESTORE_OVERLAY_POLL_INTERVAL_MS": 170,
    "MDEXPLORE_PDF_DIAGRAM_PROBE_INTERVAL_MS": 220,
}


def _load_global_settings() -> dict[str, Any]:
    payload = dict(_DEFAULTS)
    try:
        raw = GLOBAL_SETTINGS_FILE.read_text(encoding="utf-8")
        parsed = json.loads(raw)
    except Exception:
        return payload
    if not isinstance(parsed, dict):
        return payload
    for key, default_value in _DEFAULTS.items():
        if key not in parsed:
            continue
        override = parsed.get(key)
        if isinstance(default_value, list):
            if isinstance(override, list):
                payload[key] = override
            continue
        if isinstance(default_value, (int, float)):
            if isinstance(override, (int, float)):
                payload[key] = override
            continue
        if isinstance(default_value, str):
            if isinstance(override, str):
                payload[key] = override
            continue
    return payload


_SETTINGS = _load_global_settings()


def _setting(name: str) -> Any:
    return _SETTINGS.get(name, _DEFAULTS[name])


CONFIG_FILE_NAME = str(_setting("CONFIG_FILE_NAME"))
UI_ASSET_DIR = PROJECT_ROOT / str(_setting("UI_ASSET_DIR_RELATIVE"))
JS_ASSET_DIR = PROJECT_ROOT / str(_setting("JS_ASSET_DIR_RELATIVE"))
TEMPLATE_ASSET_DIR = PROJECT_ROOT / str(_setting("TEMPLATE_ASSET_DIR_RELATIVE"))
SEARCH_CLOSE_WORD_GAP = int(_setting("SEARCH_CLOSE_WORD_GAP"))
PDF_LANDSCAPE_PAGE_TOKEN = str(_setting("PDF_LANDSCAPE_PAGE_TOKEN"))
PDF_EXPORT_PRECHECK_MAX_ATTEMPTS = int(_setting("PDF_EXPORT_PRECHECK_MAX_ATTEMPTS"))
PDF_EXPORT_PRECHECK_INTERVAL_MS = int(_setting("PDF_EXPORT_PRECHECK_INTERVAL_MS"))
MERMAID_CACHE_JSON_TOKEN = str(_setting("MERMAID_CACHE_JSON_TOKEN"))
DIAGRAM_VIEW_STATE_JSON_TOKEN = str(_setting("DIAGRAM_VIEW_STATE_JSON_TOKEN"))
MERMAID_SVG_CACHE_MAX_ENTRIES = int(_setting("MERMAID_SVG_CACHE_MAX_ENTRIES"))
MERMAID_SVG_MAX_CHARS = int(_setting("MERMAID_SVG_MAX_CHARS"))
PLANTUML_RESTORE_BATCH_SIZE = int(_setting("PLANTUML_RESTORE_BATCH_SIZE"))
MERMAID_CACHE_RESTORE_BATCH_SIZE = int(_setting("MERMAID_CACHE_RESTORE_BATCH_SIZE"))
RESTORE_OVERLAY_TIMEOUT_SECONDS = float(_setting("RESTORE_OVERLAY_TIMEOUT_SECONDS"))
RESTORE_OVERLAY_SHOW_DELAY_MS = int(_setting("RESTORE_OVERLAY_SHOW_DELAY_MS"))
RESTORE_OVERLAY_MAX_VISIBLE_SECONDS = float(_setting("RESTORE_OVERLAY_MAX_VISIBLE_SECONDS"))
MERMAID_BACKEND_JS = str(_setting("MERMAID_BACKEND_JS"))
MERMAID_BACKEND_RUST = str(_setting("MERMAID_BACKEND_RUST"))
MIN_PRINT_DIAGRAM_FONT_PT = int(_setting("MIN_PRINT_DIAGRAM_FONT_PT"))
MAX_PRINT_DIAGRAM_FONT_PT = float(_setting("MAX_PRINT_DIAGRAM_FONT_PT"))
PDF_PRINT_HEADING_TO_DIAGRAM_GAP_PX = int(_setting("PDF_PRINT_HEADING_TO_DIAGRAM_GAP_PX"))
PDF_PRINT_LAYOUT_SAFETY_PX = int(_setting("PDF_PRINT_LAYOUT_SAFETY_PX"))
PDF_PRINT_KEEP_MIN_HEIGHT_PX = int(_setting("PDF_PRINT_KEEP_MIN_HEIGHT_PX"))
PDF_PRINT_PORTRAIT_LETTER_WIDTH_PX = int(_setting("PDF_PRINT_PORTRAIT_LETTER_WIDTH_PX"))
PDF_PRINT_PORTRAIT_LETTER_HEIGHT_PX = int(_setting("PDF_PRINT_PORTRAIT_LETTER_HEIGHT_PX"))
PDF_PRINT_LANDSCAPE_LETTER_WIDTH_PX = int(_setting("PDF_PRINT_LANDSCAPE_LETTER_WIDTH_PX"))
PDF_PRINT_LANDSCAPE_LETTER_HEIGHT_PX = int(_setting("PDF_PRINT_LANDSCAPE_LETTER_HEIGHT_PX"))
PDF_PRINT_HORIZONTAL_MARGIN_PX = int(_setting("PDF_PRINT_HORIZONTAL_MARGIN_PX"))
PDF_PRINT_VERTICAL_MARGIN_PX = int(_setting("PDF_PRINT_VERTICAL_MARGIN_PX"))
PDF_PRINT_PORTRAIT_MIN_WIDTH_PX = int(_setting("PDF_PRINT_PORTRAIT_MIN_WIDTH_PX"))
PDF_PRINT_PORTRAIT_MIN_HEIGHT_PX = int(_setting("PDF_PRINT_PORTRAIT_MIN_HEIGHT_PX"))
PDF_PRINT_LANDSCAPE_MIN_WIDTH_PX = int(_setting("PDF_PRINT_LANDSCAPE_MIN_WIDTH_PX"))
PDF_PRINT_LANDSCAPE_MIN_HEIGHT_PX = int(_setting("PDF_PRINT_LANDSCAPE_MIN_HEIGHT_PX"))
PDF_PRINT_WIDE_DIAGRAM_ASPECT_RATIO = float(_setting("PDF_PRINT_WIDE_DIAGRAM_ASPECT_RATIO"))
PDF_PRINT_WIDE_DIAGRAM_LANDSCAPE_GAIN = float(_setting("PDF_PRINT_WIDE_DIAGRAM_LANDSCAPE_GAIN"))
PDF_PRINT_PLANTUML_LANDSCAPE_ASPECT_RATIO = float(_setting("PDF_PRINT_PLANTUML_LANDSCAPE_ASPECT_RATIO"))
PREVIEW_SETHTML_MAX_BYTES = int(_setting("PREVIEW_SETHTML_MAX_BYTES"))
SVG_ICON_RENDER_OVERSAMPLE = int(_setting("SVG_ICON_RENDER_OVERSAMPLE"))
SVG_ICON_ALPHA_CUTOFF = int(_setting("SVG_ICON_ALPHA_CUTOFF"))
SEARCH_HIT_COUNT_FONT_PATHS = tuple(str(value) for value in _setting("SEARCH_HIT_COUNT_FONT_PATHS"))
PREVIEW_PERSISTENT_HIGHLIGHT_COLOR = str(_setting("PREVIEW_PERSISTENT_HIGHLIGHT_COLOR"))
PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_COLOR = str(_setting("PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_COLOR"))
PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_TEXT_COLOR = str(_setting("PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_TEXT_COLOR"))
PREVIEW_PERSISTENT_HIGHLIGHT_MARKER_COLOR = str(_setting("PREVIEW_PERSISTENT_HIGHLIGHT_MARKER_COLOR"))
PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_MARKER_COLOR = str(_setting("PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_MARKER_COLOR"))
PREVIEW_HIGHLIGHT_KIND_NORMAL = str(_setting("PREVIEW_HIGHLIGHT_KIND_NORMAL"))
PREVIEW_HIGHLIGHT_KIND_IMPORTANT = str(_setting("PREVIEW_HIGHLIGHT_KIND_IMPORTANT"))
PREVIEW_ZOOM_STEP = float(_setting("PREVIEW_ZOOM_STEP"))
PREVIEW_ZOOM_MIN = float(_setting("PREVIEW_ZOOM_MIN"))
PREVIEW_ZOOM_MAX = float(_setting("PREVIEW_ZOOM_MAX"))
PREVIEW_ZOOM_RESET = float(_setting("PREVIEW_ZOOM_RESET"))
PREVIEW_ZOOM_OVERLAY_TIMEOUT_MS = int(_setting("PREVIEW_ZOOM_OVERLAY_TIMEOUT_MS"))
MDEXPLORE_MAX_DOCUMENT_VIEWS = int(_setting("MDEXPLORE_MAX_DOCUMENT_VIEWS"))
MDEXPLORE_MAX_RECENT_ROOT_DIRECTORIES = int(_setting("MDEXPLORE_MAX_RECENT_ROOT_DIRECTORIES"))
MDEXPLORE_RECENT_ROOT_MENU_MRU_COUNT = int(_setting("MDEXPLORE_RECENT_ROOT_MENU_MRU_COUNT"))
MDEXPLORE_MIN_RECENT_ROOT_DWELL_SECONDS = float(_setting("MDEXPLORE_MIN_RECENT_ROOT_DWELL_SECONDS"))
MDEXPLORE_CONFIG_LOCK_STALE_SECONDS = float(_setting("MDEXPLORE_CONFIG_LOCK_STALE_SECONDS"))
MDEXPLORE_VIEWS_FILE_NAME = str(_setting("MDEXPLORE_VIEWS_FILE_NAME"))
MDEXPLORE_HIGHLIGHTING_FILE_NAME = str(_setting("MDEXPLORE_HIGHLIGHTING_FILE_NAME"))
MDEXPLORE_CONFIG_DEFAULT_ROOT_KEY = str(_setting("MDEXPLORE_CONFIG_DEFAULT_ROOT_KEY"))
MDEXPLORE_CONFIG_RECENT_ROOTS_KEY = str(_setting("MDEXPLORE_CONFIG_RECENT_ROOTS_KEY"))
MDEXPLORE_CONFIG_COPY_BASE64_IMAGES_ENABLED_KEY = str(_setting("MDEXPLORE_CONFIG_COPY_BASE64_IMAGES_ENABLED_KEY"))
MDEXPLORE_DEBUG_LOG_FILE_NAME = str(_setting("MDEXPLORE_DEBUG_LOG_FILE_NAME"))
MDEXPLORE_DEBUG_LOG_MAX_LINES = int(_setting("MDEXPLORE_DEBUG_LOG_MAX_LINES"))
_mdexplore_highlight_colors = tuple(
    (
        str(pair[0]),
        str(pair[1]),
    )
    for pair in _setting("MDEXPLORE_HIGHLIGHT_COLORS")
    if isinstance(pair, list) and len(pair) == 2
)
if _mdexplore_highlight_colors:
    MDEXPLORE_HIGHLIGHT_COLORS = _mdexplore_highlight_colors
else:
    MDEXPLORE_HIGHLIGHT_COLORS = tuple(
        (str(pair[0]), str(pair[1]))
        for pair in _DEFAULTS["MDEXPLORE_HIGHLIGHT_COLORS"]
    )
_mdexplore_search_threads = int(_setting("MDEXPLORE_DEFAULT_SEARCH_SCAN_MAX_THREADS"))
if _mdexplore_search_threads > 0:
    MDEXPLORE_DEFAULT_SEARCH_SCAN_MAX_THREADS = _mdexplore_search_threads
else:
    MDEXPLORE_DEFAULT_SEARCH_SCAN_MAX_THREADS = max(4, min(24, (os.cpu_count() or 2) * 3))
_mdexplore_base64_threads = int(_setting("MDEXPLORE_DEFAULT_BASE64_IMAGE_WORKER_THREADS"))
if _mdexplore_base64_threads > 0:
    MDEXPLORE_DEFAULT_BASE64_IMAGE_WORKER_THREADS = _mdexplore_base64_threads
else:
    MDEXPLORE_DEFAULT_BASE64_IMAGE_WORKER_THREADS = max(2, min(24, (os.cpu_count() or 2) * 2))
MDEXPLORE_PREVIEW_HTTP_CACHE_MAX_BYTES = int(_setting("MDEXPLORE_PREVIEW_HTTP_CACHE_MAX_BYTES"))
MDEXPLORE_PREVIEW_HTTP_CACHE_MAX_BYTES_QT_MAX = int(_setting("MDEXPLORE_PREVIEW_HTTP_CACHE_MAX_BYTES_QT_MAX"))
MDEXPLORE_PREVIEW_HTTP_CACHE_MIN_BYTES = int(_setting("MDEXPLORE_PREVIEW_HTTP_CACHE_MIN_BYTES"))
MDEXPLORE_PREVIEW_HTTP_CACHE_FREE_SPACE_RESERVE_BYTES = int(_setting("MDEXPLORE_PREVIEW_HTTP_CACHE_FREE_SPACE_RESERVE_BYTES"))
MDEXPLORE_PREVIEW_WEBENGINE_INSTANCE_STALE_SECONDS = int(_setting("MDEXPLORE_PREVIEW_WEBENGINE_INSTANCE_STALE_SECONDS"))
MDEXPLORE_INLINE_DATA_IMAGE_POOL_THREADS = int(_setting("MDEXPLORE_INLINE_DATA_IMAGE_POOL_THREADS"))
MDEXPLORE_TREE_MARKER_SCAN_POOL_THREADS = int(_setting("MDEXPLORE_TREE_MARKER_SCAN_POOL_THREADS"))
MDEXPLORE_PLANTUML_POOL_MAX_THREADS = int(_setting("MDEXPLORE_PLANTUML_POOL_MAX_THREADS"))
MDEXPLORE_PDF_POOL_MAX_THREADS = int(_setting("MDEXPLORE_PDF_POOL_MAX_THREADS"))
MDEXPLORE_MATCH_TIMER_INTERVAL_MS = int(_setting("MDEXPLORE_MATCH_TIMER_INTERVAL_MS"))
MDEXPLORE_TREE_SEARCH_REFRESH_DEBOUNCE_MS = int(_setting("MDEXPLORE_TREE_SEARCH_REFRESH_DEBOUNCE_MS"))
MDEXPLORE_SCROLL_CAPTURE_INTERVAL_MS = int(_setting("MDEXPLORE_SCROLL_CAPTURE_INTERVAL_MS"))
MDEXPLORE_DIAGRAM_STATE_CAPTURE_INTERVAL_MS = int(_setting("MDEXPLORE_DIAGRAM_STATE_CAPTURE_INTERVAL_MS"))
MDEXPLORE_PREVIEW_ACTION_POLL_INTERVAL_MS = int(_setting("MDEXPLORE_PREVIEW_ACTION_POLL_INTERVAL_MS"))
MDEXPLORE_STATUS_IDLE_INTERVAL_MS = int(_setting("MDEXPLORE_STATUS_IDLE_INTERVAL_MS"))
MDEXPLORE_FILE_CHANGE_WATCH_INTERVAL_MS = int(_setting("MDEXPLORE_FILE_CHANGE_WATCH_INTERVAL_MS"))
MDEXPLORE_RESTORE_OVERLAY_POLL_INTERVAL_MS = int(_setting("MDEXPLORE_RESTORE_OVERLAY_POLL_INTERVAL_MS"))
MDEXPLORE_PDF_DIAGRAM_PROBE_INTERVAL_MS = int(_setting("MDEXPLORE_PDF_DIAGRAM_PROBE_INTERVAL_MS"))
