"""Shared runtime constants for mdexplore."""

from __future__ import annotations

from pathlib import Path

CONFIG_FILE_NAME = ".mdexplore.cfg"
PROJECT_ROOT = Path(__file__).resolve().parent.parent
UI_ASSET_DIR = PROJECT_ROOT / "assets" / "ui"
JS_ASSET_DIR = PROJECT_ROOT / "assets" / "js"
SEARCH_CLOSE_WORD_GAP = 50
PDF_LANDSCAPE_PAGE_TOKEN = "MDEXPLORE_LANDSCAPE_PAGE_TOKEN"
PDF_EXPORT_PRECHECK_MAX_ATTEMPTS = 60
PDF_EXPORT_PRECHECK_INTERVAL_MS = 140
MERMAID_CACHE_JSON_TOKEN = "__MDEXPLORE_MERMAID_CACHE_JSON__"
DIAGRAM_VIEW_STATE_JSON_TOKEN = "__MDEXPLORE_DIAGRAM_VIEW_STATE_JSON__"
MERMAID_SVG_CACHE_MAX_ENTRIES = 256
MERMAID_SVG_MAX_CHARS = 250_000
PLANTUML_RESTORE_BATCH_SIZE = 2
MERMAID_CACHE_RESTORE_BATCH_SIZE = 2
RESTORE_OVERLAY_TIMEOUT_SECONDS = 25.0
RESTORE_OVERLAY_SHOW_DELAY_MS = 350
RESTORE_OVERLAY_MAX_VISIBLE_SECONDS = 1.0
MERMAID_BACKEND_JS = "js"
MERMAID_BACKEND_RUST = "rust"
MIN_PRINT_DIAGRAM_FONT_PT = 3
MAX_PRINT_DIAGRAM_FONT_PT = 12.0
PDF_PRINT_HEADING_TO_DIAGRAM_GAP_PX = 16
PDF_PRINT_LAYOUT_SAFETY_PX = 40
PDF_PRINT_KEEP_MIN_HEIGHT_PX = 120
PDF_PRINT_PORTRAIT_LETTER_WIDTH_PX = 1000
PDF_PRINT_PORTRAIT_LETTER_HEIGHT_PX = 1310
PDF_PRINT_LANDSCAPE_LETTER_WIDTH_PX = 1100
PDF_PRINT_LANDSCAPE_LETTER_HEIGHT_PX = 860
PDF_PRINT_HORIZONTAL_MARGIN_PX = 80
PDF_PRINT_VERTICAL_MARGIN_PX = 130
PDF_PRINT_PORTRAIT_MIN_WIDTH_PX = 320
PDF_PRINT_PORTRAIT_MIN_HEIGHT_PX = 320
PDF_PRINT_LANDSCAPE_MIN_WIDTH_PX = 360
PDF_PRINT_LANDSCAPE_MIN_HEIGHT_PX = 260
PDF_PRINT_WIDE_DIAGRAM_ASPECT_RATIO = 1.19
PDF_PRINT_WIDE_DIAGRAM_LANDSCAPE_GAIN = 1.06
PDF_PRINT_PLANTUML_LANDSCAPE_ASPECT_RATIO = 1.18
PREVIEW_SETHTML_MAX_BYTES = 650_000
SVG_ICON_RENDER_OVERSAMPLE = 4
SVG_ICON_ALPHA_CUTOFF = 1
SEARCH_HIT_COUNT_FONT_PATHS = (
    str(UI_ASSET_DIR / "LiberationSansNarrow-Regular.ttf"),
    "/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf",
)
PREVIEW_PERSISTENT_HIGHLIGHT_COLOR = "rgba(102, 86, 178, 0.36)"
PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_COLOR = "rgba(225, 214, 255, 0.76)"
PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_TEXT_COLOR = "#170534"
PREVIEW_PERSISTENT_HIGHLIGHT_MARKER_COLOR = "rgba(112, 90, 188, 0.92)"
PREVIEW_PERSISTENT_HIGHLIGHT_IMPORTANT_MARKER_COLOR = "rgba(154, 132, 220, 0.96)"
PREVIEW_HIGHLIGHT_KIND_NORMAL = "normal"
PREVIEW_HIGHLIGHT_KIND_IMPORTANT = "important"
PREVIEW_ZOOM_STEP = 0.1
PREVIEW_ZOOM_MIN = 0.35
PREVIEW_ZOOM_MAX = 3.0
PREVIEW_ZOOM_RESET = 1.0
PREVIEW_ZOOM_OVERLAY_TIMEOUT_MS = 850
